app:
  isDebug: true
  inMemory: false
  avatarPath: "./uploads/"
server:
  host: ""
  port: 8080
yandex:
  trKey: "Bearer t1.9euelZrOmc2Kz86UnMqJi8mempDIme3rnpWanMyVzMzLyJuXnJSQzZSQzJnl9PdFGCRN-e9IGxma3fT3BUchTfnvSBsZms3n9euelZqSkJWMypmKj5Wei82Ok8_JjO_8xeuelZqSkJWMypmKj5Wei82Ok8_JjA.8PYdrYfX-yxZjH1ZIhKaqx9tO9ferA-agBSb6PhxPAEEReGZuNPVZRkvp8RU-9E6EMFN5SGDY1u6vh4hEKUoDQ"
  url: "https://translate.api.cloud.yandex.net/translate/v2/translate"
  folderId: "b1gq4i9e5unl47m0kj5f"
  header: "application/json"
  method: "POST"
gpt:
  trKey: "Bearer t1.9euelZrOmc2Kz86UnMqJi8mempDIme3rnpWanMyVzMzLyJuXnJSQzZSQzJnl9PdFGCRN-e9IGxma3fT3BUchTfnvSBsZms3n9euelZqSkJWMypmKj5Wei82Ok8_JjO_8xeuelZqSkJWMypmKj5Wei82Ok8_JjA.8PYdrYfX-yxZjH1ZIhKaqx9tO9ferA-agBSb6PhxPAEEReGZuNPVZRkvp8RU-9E6EMFN5SGDY1u6vh4hEKUoDQ"
  url: "https://llm.api.cloud.yandex.net/foundationModels/v1/completion"
  folderId: "b1gq4i9e5unl47m0kj5f"
  header: "application/json"
  method: "POST"