app:
  isDebug: true
  inMemory: false
  avatarPath: "./uploads/"
server:
  host: ""
  port: 8080
yandex:
  trKey: "Bearer "
  url: "https://translate.api.cloud.yandex.net/translate/v2/translate"
  folderId: "b1gq4i9e5unl47m0kj5f"
  header: "application/json"
  method: "POST"
gpt:
  trKey: "Bearer "
  url: "https://llm.api.cloud.yandex.net/foundationModels/v1/completion"
  folderId: "b1gq4i9e5unl47m0kj5f"
  header: "application/json"
  method: "POST"
