app:
  isDebug: true
  inMemory: false
  avatarPath: "./uploads/"
server:
  host: ""
  port: 8080
yandex:
  trKey: "Bearer t1.9euelZrImMyXy5XPjcubys-Vy5iTnu3rnpWanMyVzMzLyJuXnJSQzZSQzJnl9PdaJi5N-e83GHHj3fT3GlUrTfnvNxhx483n9euelZrNzJ7GksjJkI6NlcjGkpHPje_8xeuelZrNzJ7GksjJkI6NlcjGkpHPjQ.q5P6abLiO1ZP1mMQVGg0rq55Vu7Yt1fwsJbXuQz2Hi22necGgTO3tRnrZLQQl6Bs2us89LO-MrSsK0Qw_3v1BQ"
  url: "https://translate.api.cloud.yandex.net/translate/v2/translate"
  folderId: "b1gq4i9e5unl47m0kj5f"
  header: "application/json"
  method: "POST"