app:
  isDebug: true
  inMemory: false
  avatarPath: "./uploads/"
server:
  host: ""
  port: 8080
yandex:
  trKey: "Bearer t1.9euelZrOls-UncuQyceMiZmQx5iZku3rnpWanMyVzMzLyJuXnJSQzZSQzJnl9PcYQxhN-e86TWft3fT3WHEVTfnvOk1n7c3n9euelZqbyI3LnY2VkI7MlMnLzo_NkO_8xeuelZqbyI3LnY2VkI7MlMnLzo_NkA.ZIsz8rf7u_XQ68ekRGot4P_QqUS1lX9lc4ImOCWWTL69sfXLXXw4DakpugZg3wYlsrDVN_JSZNbTwAM6NqTRBA"
  url: "https://translate.api.cloud.yandex.net/translate/v2/translate"
  folderId: "b1gq4i9e5unl47m0kj5f"
  header: "application/json"
  method: "POST"
gpt:
  trKey: "Bearer t1.9euelZrOls-UncuQyceMiZmQx5iZku3rnpWanMyVzMzLyJuXnJSQzZSQzJnl9PcYQxhN-e86TWft3fT3WHEVTfnvOk1n7c3n9euelZqbyI3LnY2VkI7MlMnLzo_NkO_8xeuelZqbyI3LnY2VkI7MlMnLzo_NkA.ZIsz8rf7u_XQ68ekRGot4P_QqUS1lX9lc4ImOCWWTL69sfXLXXw4DakpugZg3wYlsrDVN_JSZNbTwAM6NqTRBA"
  url: "https://llm.api.cloud.yandex.net/foundationModels/v1/completion"
  folderId: "b1gq4i9e5unl47m0kj5f"
  header: "application/json"
  method: "POST"