version: "3.8"

services:
  #  web:
  #    # TODO: start go server
  #    expose:
  #      - 8000
  #    env_file:
  #      - ./.env/dev/.env.web
  #    depends_on:
  #      - postgres
  postgres:
    image: postgres:16.2
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - "8888:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/postgresql.conf:/etc/postgresql.conf
    #      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env/dev/.env.db

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./metrics/prometheus:/etc/prometheus"
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - "./metrics/grafana/grafana.ini:/etc/grafana/grafana.ini"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Artem557 # Задайте свой пароль
      - GF_SECURITY_ADMIN_USER=admin     # Задайте свое имя пользователя
    depends_on:
      - prometheus
volumes:
  grafana_data:




