version: "3.8"

services:
  #  web:
  #    # TODO: start go server
  #    expose:
  #      - 8000
  #    env_file:
  #      - ./.env/dev/.env.web
  #    depends_on:
  #      - postgres
  postgres:
    image: postgres:16.2
    ports:
      - "8888:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    #      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env/dev/.env.db

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./metrics/prometheus:/etc/prometheus"

