app:
  isDebug: true
  inMemory: false
  avatarPath: "./uploads/"
server:
  host: ""
  port: 8080
yandex:
  trKey: "Bearer t1.9euelZqJz4qPkseUxouQnJrGmo-XlO3rnpWanMyVzMzLyJuXnJSQzZSQzJnl9PdeBitO-e84LjXG3fT3HjUoTvnvOC41xs3n9euelZqSj5HMio2KzMyOmpmal4nHne_8xeuelZqSj5HMio2KzMyOmpmal4nHnQ.vEtdXUvxOgDHl2ltJ88L1rS2xCUeVa12TyggR5k8c6KyfRBiYzPZYXeTvJ1uVEW0fZAXeU2R-zp2b7xHnRcqDQ"
  url: "https://translate.api.cloud.yandex.net/translate/v2/translate"
  folderId: "b1gq4i9e5unl47m0kj5f"
  header: "application/json"
  method: "POST"