app:
  isDebug: true
  inMemory: false
  avatarPath: "./uploads/"
server:
  host: ""
  port: 8080
yandex:
  trKey: "Bearer t1.9euelZqNm57Kl8nPzY-KzYyOjY7Il-3rnpWanMyVzMzLyJuXnJSQzZSQzJnl9Pcfb0VO-e82fE_i3fT3Xx1DTvnvNnxP4s3n9euelZqJk8yTiciczYudkY-Nlp7JkO_8xeuelZqJk8yTiciczYudkY-Nlp7JkA.CUKAh50i-aABIxT04MylizKrpE44EMwr9S7YWNZ4dxtWpza1sc_73cneYiRoHW6Y6WyTSlHy2rzpvQtnQ1X9Dg"
  url: "https://translate.api.cloud.yandex.net/translate/v2/translate"
  folderId: "b1gq4i9e5unl47m0kj5f"
  header: "application/json"
  method: "POST"