app:
  isDebug: false
  inMemory: false
  avatarPath: "./uploads/"
server:
  host: ""
  port: 8080
yandex:
  trKey: "Bearer t1.9euelZqelYrMyciLnJDHj5PKzpyclO3rnpWanMyVzMzLyJuXnJSQzZSQzJnl8_dlHlBO-e80ShNo_d3z9yVNTU757zRKE2j9zef1656VmozOzZPGlMidmZTHjcjNk86e7_zF656VmozOzZPGlMidmZTHjcjNk86e.dbhRbkheLJfmVeunG45CqjxpeIosd9qEl3g0HlRvQSQBnn3QvPOBklVEm5GxoOUKTBWvWJIxBTsOXvRb9fOIDA"
  url: "https://translate.api.cloud.yandex.net/translate/v2/translate"
  folderId: "b1gq4i9e5unl47m0kj5f"
  header: "application/json"
  method: "POST"