app:
  isDebug: true
  inMemory: false
  avatarPath: "./uploads/"
server:
  host: ""
  port: 8080
yandex:
  trKey: "Bearer t1.9euelZrGj5CUkJCYl5vMkMjKkpONmu3rnpWanMyVzMzLyJuXnJSQzZSQzJnl8_d9NhJO-e8vNjVN_N3z9z1lD0757y82NU38zef1656VmsyPmprOzpaYipCTyZ3Kmp6R7_zF656VmsyPmprOzpaYipCTyZ3Kmp6R.pIeTpW0-vEzLCnwzwhSOX_cTSNOEc_lqBo2pAR6PQK8gosnA77nhjzQ9r3YmvnaQ7YxdLo8CQH78ALXKgsLdDg"
  url: "https://translate.api.cloud.yandex.net/translate/v2/translate"
  folderId: "b1gq4i9e5unl47m0kj5f"
  header: "application/json"
  method: "POST"