basePath: /
definitions:
  models.Error:
    properties:
      error:
        example: error description
        type: string
    type: object
  models.ErrorResponse:
    properties:
      body:
        $ref: '#/definitions/models.Error'
      status:
        example: 400
        type: integer
    type: object
  models.Response:
    properties:
      body: {}
      status:
        example: 200
        type: integer
    type: object
  models.User:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Messenger authorization API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      operationId: login
      parameters:
      - description: Email field is not mandatory for login
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Username or password wrong
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "405":
          description: Use POST
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: logs user in
  /logout:
    get:
      operationId: logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: no session to logout
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: logs user out
  /register:
    post:
      consumes:
      - application/json
      operationId: register
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Username exists or field required field empty
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "405":
          description: Use POST
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: registers user
schemes:
- http
- https
swagger: "2.0"
