definitions:
  models.Error:
    properties:
      error:
        example: user not found
        type: string
    type: object
  models.ErrorResponse:
    properties:
      body:
        $ref: '#/definitions/models.Error'
      status:
        example: 400
        type: integer
    type: object
  models.Response:
    properties:
      body: {}
      status:
        example: 200
        type: integer
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      operationId: login
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Username or password wrong
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "405":
          description: Use POST
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: logs user in
  /logout:
    get:
      operationId: logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: no session to logout
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: logs user out
  /register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      operationId: register
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Username exists or field required field empty
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "405":
          description: Use POST
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: registers user
swagger: "2.0"
